wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.5
    start_time: 1673437181.226606
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.5
      5: 0.13.8
      8:
      - 1
      - 3
      - 5
